# Set 256 colors
# set-option -g default-terminal 'screen-256color' -- Set by tmux-sensible
set-option -g terminal-overrides ',xterm-256color:RGB'

# Change ctrl-b to ctrl-a
# unbind-key C-b
set -g prefix C-a

set -g base-index 1 # start indexing windows at 1 instead of 0
set -g detach-on-destroy off # don't exit from tmux when closing a session
# set -g escape-time 0 # zero-out escape time delay -- Already set by tmux-sensible
# set -g history-limit 1000000 # increase history size (from 2000) -- set to 50000 by sensible
set -g renumber-windows on # renumber all windows when any window is closed
set -g set-clipboard on # use system clipboard
set -g status-position top
set -g default-terminal "${TERM}"
setw -g mode-keys vi

set -g mouse on # for whenever I do need the mouse

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank' # To use vi yank motion
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'catppuccin/tmux'
# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# set -g pane-active-border-style 'fg=magenta,bg=default' # ?
# set -g pane-border-style 'fg=brightblack,bg=default' # ?


# Catppuccin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
# set -g @catppuccin_pane_status_enabled "yes"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_default_fill "number"

# Make the status line prettier
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
# set -ag status-right "#{E:@catppuccin_status_battery}" # set if using battery


# Remap splitting screen
# unbind h
unbind '"'
unbind %
bind \\ split-window -h -c "#{pane_current_path}"
bind v split-window -v -c "#{pane_current_path}"

# Rename window

# Reload config file
bind R source-file ~/.config/tmux/tmux.conf

# vim-like pane resizing
unbind C-Up
unbind C-Down
unbind C-Left
unbind C-Right

bind -r C-k resize-pane -U
bind -r C-j resize-pane -D
bind -r C-h resize-pane -L
bind -r C-l resize-pane -R

# vim-like pane switching
unbind Up
unbind Down
unbind Left
unbind Right

bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
