return {
  "folke/snacks.nvim",
  opts = {
    picker = {
      sources = {
        files = {
          hidden = true,
          ignored = true,
          exclude = {
            "node_modules",
            ".git",
            "_build",
            "*.vo*",
            "*.glob",
            "*.aux",
            "*.cmi",
            "*.cmx",
            "*.cmxa",
            "*.cmxs",
            "*.cmt",
            "*.cmti",
            "*.ml.d",
            "*.mli.d",
            "*.o",
          },
        },
        explorer = {
          hidden = true,
          ignored = true,
          exclude = {
            "node_modules",
            ".git",
            "_build",
            "*.vo*",
            "*.glob",
            "*.aux",
            "*.cmi",
            "*.cmx",
            "*.cmxa",
            "*.cmxs",
            "*.cmt",
            "*.cmti",
            "*.ml.d",
            "*.mli.d",
            "*.o",
          },
        },
      },
    },
  },
}
